### ISSUE TITLE
Thanku

### ISSUE THREAD

**Issue by ghost** [IceWreck/LokiBoard-Android-Keylogger#2]

**Comment by IceWreck** [comment]
I'm not really the guy you should ask for help on a custom keyboard. 

I didnt even build this keyboard. I just forked an open source project (Simple Keyboard) and added the keylogging part to because I needed it.

You should ask someone else for help.

**Comment by salmansajjad** [comment]
Thanku for your response. I want to tell you in custom keyboard i need
keylogging also. Help me in key logging.

**Comment by salmansajjad** [comment]
sir need your response. please contact me. email: salmansajjadghumman@gmail.com

**Comment by salmansajjad** [comment]
i'm very thankful if you response me on my twitter : salmansajjad_1 . i already send you message on twitter. Thanku

**Comment by IceWreck** [comment]
The keylogging logic is [here](https://github.com/IceWreck/LokiBoard-Android-Keylogger/blob/46b40bcb0235dd633e777cf553639090053ab2e3/app/src/main/java/com/abifog/lokiboard/latin/LatinIME.java) and [here](https://github.com/IceWreck/LokiBoard-Android-Keylogger/blob/46b40bcb0235dd633e777cf553639090053ab2e3/app/src/main/java/com/abifog/lokiboard/latin/LatinIME.java)

**Comment by salmansajjad** [comment]
sir can you contact me in private chat. thankful for your response. only 5 mints need for conversation.
e-mail already mentioned.
